# Generated by Django 4.0.4 on 2022-06-11 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_alter_contact_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
